config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :posts, shallow: true do
    resources :like_posts, :comments do 
      resources :likes
    end
  end

  root to: "posts#index"

  get '/new' => 'posts#new'

  get '//posts/:post_id/comments/new' => 'comment#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :post

has_many :likes

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to posts_path
  end

  def comment_params
    params.require(:comment).permit(:comment, :thumbsup)
  end

end

app/controllers/like_posts_controller.rb
class LikePostsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
  end

  def create
    @comment = Comment.find(params[:comment_id])
    @comment.likes.create
    render json: {new_like_count: @comment.likes.count}
    # redirect_to post_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @posts = Post.all
  end

  def post_params
    params.require(:post).permit(:name, :image)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to '/posts'
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to '/posts'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted successfully'
    redirect_to '/posts'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_posts_helper.rb
module LikePostsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.label :thumbsup %>
  <%= f.check_box :thumbsup %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>

  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

  <%= notice %>
  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>
  <%= f.file_field :image %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= image_tag post.image.url(:thumb) %>
    <h2> <%= link_to post.name, post_path(post) %> </h2>
    <%= link_to "Edit #{post.name}", edit_post_path(post)%>
    <%= link_to "Delete #{post.name}", post_path(post), method: :delete %>
    <%= link_to "Comment on #{post.name}", new_post_comment_path(post) %>
    <h3>comments for <%= post.name %></h3>

    <% if post.comments.any? %>
      <ul>
        <% post.comments.each do |comment| %>
          <p><%= pluralize comment.likes.count, 'like' %></p>
          <li>
            <%= comment.comment %>, <strong><%= comment.thumbsup %></strong>
            <%= link_to "Like", comment_likes_path(comment), class: 'likes-link' %>
            <span class="likes_count"> <%= comment.likes.count %> </span> <%= 'like'.pluralize(comment.likes.count) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No comments.</p>
    <% end %>
  <% end %>
<% else %>
  No posts yet
<% end %>

<a href='/new'>Add Image</a>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<p><%= @post.name %></p>